### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by maxfragg** [jpic/bashworks#1]
hey, i'd like to use parts of your xrandr script for my monitorsetup script[1] for xrandr/herbstluftwm and i'm missing any licence notice und which you are willing to share this stuff
greetings
MaxFragg

[1]https://github.com/maxfragg/dotfiles/blob/master/bin/display_menu.sh

**Comment by jpic** [comment]
Thanks for your feedback, I believe MIT license would do, if it doesn't please let me know.
